---
name: Upload Git README to Dockerhub
description: Processes includes and sends the result to Dockerhub
inputs:
  dockerhub_username:
    required: true
    description: "Username for Dockerhub"
  dockerhub_password:
    required: true
    description: "Password for Dockerhub"
  dockerhub_repository:
    required: true
    description: "Repository for Dockerhub"
  decription_file:
    required: false
    description: "File to upload"
    default: "README.md"
runs:
  using: 'docker'
  image: 'docker://proum/dockerhub-description:latest'
  env:
    DOCKERHUB_USERNAME: ${{ inputs.dockerhub_username }}
    DOCKERHUB_PASSWORD: ${{ inputs.dockerhub_password }}
    DOCKERHUB_REPOSITORY: ${{ inputs.dockerhub_repository }}
    DESCRIPTION_FILE: ${{ inputs.decription_file }}
  args:
    - "--pipeline"
