---
name: Lint markdown
description: Lints every markdown file
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - mdl
    - ./
outputs:
  hints:
    description: 'List of markdown lint findings'
