---
name: Lint YAML
description: Lints every YAML file
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - yamllint
    - -d
    - relaxed
    - ./
outputs:
  hints:
    description: 'List of YAML lint findings'
